---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

dc_name: CAMPUS1_FABRIC

# Spine Switches
spine:
  defaults:
    platform: vEOS-LAB
    loopback_ipv4_pool: 100.64.11.0/24
    bgp_as: "65001"
    evpn_route_servers: [ dc1-spine1, dc1-spine2 ]
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  nodes:
    cmp1-spine1:
      # evpn_role: server
      id: 1
      mgmt_ip: 192.168.0.21/24
    cmp1-spine2:
      # evpn_role: server
      id: 2
      mgmt_ip: 192.168.0.22/24

l3leaf:
  defaults:
    virtual_router_mac_address: 00:1c:73:00:dc:00
    platform: vEOS-LAB
    loopback_ipv4_pool: 100.64.11.0/24
    loopback_ipv4_offset: 10
    vtep_loopback_ipv4_pool: 100.64.12.0/24
    max_uplink_switches: 4
    uplink_switches: [ cmp1-spine1, cmp1-spine2 ]
    uplink_interfaces: [ Ethernet3, Ethernet4 ]
    uplink_ipv4_pool: 100.64.10.0/24
    mlag_interfaces: [ Ethernet1, Ethernet2 ]
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    evpn_route_servers: [ cmp1-spine1, cmp1-spine2 ]
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    mlag_peer_l3_ipv4_pool: 100.64.13.0/24
    mlag_peer_ipv4_pool: 100.64.14.0/24
  node_groups:
    # Server leafs definition
    cmp1-leaf1:
      bgp_as: "65101"
      filter:
        tenants: [ CMP_TENANT ]
        tags: [ campus ]
      nodes:
        cmp1-leaf1a:
          id: 1
          mgmt_ip: 192.168.0.123/24
          uplink_switch_interfaces: [ Ethernet3, Ethernet3 ]
        cmp1-leaf1b:
          id: 2
          mgmt_ip: 192.168.0.124/24
          uplink_switch_interfaces: [ Ethernet4, Ethernet4 ]
    cmp1-leaf2:
      bgp_as: "65102"
      filter:
        tenants: [ CMP_TENANT ]
        tags: [ campus ]
      nodes:
        cmp1-leaf2a:
          id: 3
          mgmt_ip: 192.168.0.125/24
          uplink_switch_interfaces: [ Ethernet5, Ethernet5 ]
        cmp1-leaf2b:
          id: 4
          mgmt_ip: 192.168.0.126/24
          uplink_switch_interfaces: [ Ethernet6, Ethernet6 ]
    # Border leafs definition
    cmp1-borderleaf1:
      bgp_as: "65103"
      uplink_switches: [ cmp1-spine1, cmp1-spine2, dc1-bleaf1a, dc1-bleaf1b ]
      uplink_interfaces: [ Ethernet3, Ethernet4, Ethernet5, Ethernet6 ]
      filter:
        tenants: [ CMP_TENANT ]
        tags: [ campus ]
      nodes:
        cmp1-bleaf1a:
          id: 5
          mgmt_ip: 192.168.0.121/24
          uplink_switch_interfaces: [ Ethernet1, Ethernet1, Ethernet5, Ethernet5 ]
        cmp1-bleaf1b:
          id: 6
          mgmt_ip: 192.168.0.122/24
          uplink_switch_interfaces: [ Ethernet2, Ethernet2, Ethernet6, Ethernet6 ]


l2leaf:
  defaults:
    platform: vEOS-LAB
    uplink_switches: [ cmp1-leaf1a, cmp1-leaf1b ]
    uplink_interfaces: [ Ethernet3, Ethernet4 ]
    mlag_interfaces: [ Ethernet1, Ethernet2 ]
    spanning_tree_priority: 8192
    spanning_tree_mode: mstp
    mlag_peer_ipv4_pool: 100.64.15.0/24
  node_groups:
    cmp1-l2leaf1:
      filter:
        tenants: [ CMP_TENANT ]
        tags: [ campus ]
      nodes:
        cmp1-l2leaf1a:
          id: 1
          mgmt_ip: 192.168.0.127/24
          uplink_switch_interfaces: [ Ethernet5, Ethernet5 ]
        cmp1-l2leaf1b:
          id: 2
          mgmt_ip: 192.168.0.128/24
          uplink_switch_interfaces: [ Ethernet6, Ethernet6 ]